### ISSUE TITLE
Allowing delayed check for jump/branch instructions

### ISSUE THREAD

**Issue by kliuMsft** [microsoft/cheriot-sail#23]
In the case of branch/jump instructions, would like to have the option to delay the PCC-based branch target checks (address bound/permission) to instruction fetch time (errors associated with the branch target instruction), rather than handling it at EX time (error associated with the branch/jump themselves).

The benefit is better performance (checking logic will not be in the critical instruction feth timing path, for example) and fewer changes to execution logic (espically branch instructions).

**Comment by rmn30** [comment]
I think I agree that delaying the bounds check until instruction fetch of the target PC makes sense, even though it potentially makes debugging harder. In many cases the link register will indicate the offending instruction, so hopefully this isn't too big a problem (certainly no worse the before CHERI!). The major exception to this is returns (`cret`) which will mostly target sealed capabilities. Can we keep the tagged and unsealed checks on the jump / branch? Other jumps / branches without link are likely to have immediate offsets which are much less likely to go out of bounds if linking and PCC are correct.

Note that removing the bounds check will also solve https://github.com/microsoft/cheriot-sail/issues/18 .

**Comment by rmn30** [comment]
Note that @vmurali has in mind a JIT compiler / dynamic linker where trap at the destination may not be sufficient.

**Comment by kliuMsft** [comment]
@rmn30 for register-targeted jumps (jr/jalr) I don't see any issues with doing tag/unseal checks at EX time. The performance concerns are mostly with address bound checking. So we can,
 - For c.JR/JALR, keep the tag/unsealed checking but defer address bound checking to fetching 
 - For all other PCC-based jump/branches (conditioanl branching and JAL), defer all checks to fetching
Does this sound right?

**Comment by vmurali** [comment]
One has to store the previous PC in case of taken branches/jumps in MEPCC (or have a different architectural register storing the previous PC) to as suggested in https://github.com/microsoft/cheriot-sail/issues/18, to make debugging simpler.

**Comment by vmurali** [comment]
I posted a comment on #18. Basically JALRs, JALs and Branches would now need a representability check :(.

My strong preference would be to just have a PrevPC SCR that is set only on taken branches and jumps (and is set to untagged cap otherwise).

**Comment by vmurali** [comment]
I was revisiting this situation in our Kami implementation. Doing representability check is essentially almost the same as doing a bounds check (we avoid a few comparisons, but we still have to obtain `a_top - a_hi`), so we can't avoid doing a check for PC cap in execute. Instead I propose the following (where I front-load all the checks during execute and avoid all checks in fetch). I feel the entire situation can be much simpler if we just didn't have compressed instructions (and instead went with the better compressed instruction extensions that fuses two or more instructions without introducing 16 bit instructions).

1. Check for PC+4 always, irrespective of whether we support compressed instructions or not.
- Security hole: Trampolines using compressed jumps/branches followed by a valid (compressed) instruction the caller shouldn't have access too is now accessible by the caller.
-- Remedy 1: All jump/branch targets should be 4-bytes aligned - this can also let us omit 2 LSB bits instead of 1 bit for branches/jumps. This could lead to slightly worse codegen to fill the gaps for jump/branch targets with No-ops. And this still doesn't solve the situation when the caller has write permissions to a 2-byte trampoline which they can change to be a fall through instruction, executing the next instruction for which they morally didn't have permissions to execute.
-- Remedy 2: Compressed instructions are not allowed for jumps and branches. This fixes the hole completely at the cost of slightly worse codegen. (I agree this hole is not that serious to warrant a fix like this; but you never know what can be exploited!).

2. Avoid tag, permission *and bounds* checks during fetch: There are 2 places where the PC cap meta data changes:
- JALR instruction: tag, permission and bounds (+4) can be checked when executing the JALR instruction (this is being done now, except for bounds+4 instead of bounds+2 check).
- MRet instruction when MEPCC has bad tag/permission/bounds: Exceptions are raised if the MEPCC has bad tag/permission. Regarding bounds, we need to know if the original instruction which caused the exception is 2-bytes or 4-bytes - we can store that info (or the entire instruction) in another System CSR. We check the bounds against this CSR. This exposes a hole in the trap handler  where the trap handler can manipulate the new CSR and do a more relaxed bounds check - we should ensure/formally prove that the trap handler doesn't do that. MRet must also ensure that MTCC is has correct tag/permission/bounds such that a future Exception or ECall will go to the correct trap handler. It will raise a new exception if that were not the case. And regarding bounds, MTCC+4 will be checked if it stays within bounds. We will require that MTCC+4 also lies within the trap handler. Now, we just have to check for the initial value of MTCC to have the correct tag/permission/bounds.

If one didn't support compressed instructions, all these checks become pretty palatable (Point 1 goes away completely, and for Point 2, we don't need extra System CSRs in the MRet test).

Note: Kunyan mentioned that he wanted to move all bounds checking to fetch. This does the exact opposite (moves everything out of fetch into execute). Just to reiterate, it is impossible to avoid either representability or bounds check for branch/jumps in execute. Sorry for the long comment.

**Comment by vmurali** [comment]
Haha, realized that avoiding bounds check during fetch wouldn't catch PC+4 going out of bounds :). So scratch the entire alternative, and stick with the current design.

**Comment by vmurali** [comment]
I am not sure how just clearing the tag bit in MEPCC is sufficient when a Branch/JAL/JALR target is unrepresentable (especially Branch and JAL). It could be unrepresentable in such a way that the bounds check with the new address would pass during instruction fetch.

If the tag for MEPCC is cleared, how would one recover from Instruction Bounds Violation exception? That is, when I run MRET after handling this exception (say by changing the address to point to the previous instruction which I just rewrite in the trap handler), how will it go back to that compartment/code block?

**Comment by vmurali** [comment]
If you really want to push all of Branch/JAL/JALR bound checks into fetch, the correct way to do it is to save the previous PCC in the case of Branch and JAL, and perform a bounds check based on the previous PCC. In case of JALR, save the target PCC in the previous PCC register and perform a bounds check based on that register.

And instead of complicating the behavior of MEPCC by clearing the tag, you can just store the previous PCC in a new SCR (MEPrevPCC). Write/Read legalization is orthogonal to this change (and I agree that clearing tag whenever legalization occurs is a simpler and sufficient design choice).

**Comment by davidchisnall** [comment]
> I am not sure how just clearing the tag bit in MEPCC is sufficient when a Branch/JAL/JALR target is unrepresentable (especially Branch and JAL). It could be unrepresentable in such a way that the bounds check with the new address would pass during instruction fetch.

The bounds check will succeed, but the tag check will not.

> If the tag for MEPCC is cleared, how would one recover from Instruction Bounds Violation exception? That is, when I run MRET after handling this exception (say by changing the address to point to the previous instruction which I just rewrite in the trap handler), how will it go back to that compartment/code block?

Currently, this kind of error will always invoke the error handler or force unwind.  The error handler receives an untagged copy of the PCC (to preserve the control-flow-integrity properties of libraries and any secrecy that they enforce built atop those properties) and the switcher will rederive it form the compartment's PCC.

**Comment by rmn30** [comment]
There's an implicit assumption that the PCC bounds are stored expanded, so the representability issue only arises when we take the bounds exception on instruction fetch. In the Sail PC and PCC are separate and PCC never has its address set. The arch doc could make this clearer.

**Comment by rmn30** [comment]
> The bounds check will succeed, but the tag check will not.

Not quite. It's still a bounds failure on instruction fetch. It's only MEPCC that has tag cleared.

**Comment by vmurali** [comment]
> Currently, this kind of error will always invoke the error handler or force unwind. The error handler receives an untagged copy of the PCC (to preserve the control-flow-integrity properties of libraries and any secrecy that they enforce built atop those properties) and the switcher will rederive it form the compartment's PCC.

Okay, this looks fine.

> There's an implicit assumption that the PCC bounds are stored expanded, so the representability issue only arises when we take the bounds exception on instruction fetch.

Can you clarify this in the ISA doc? Storing PCC bounds as expanded is part of the spec now. The spec should also state that JAL and Branch do not affect the *expanded* bounds/*expanded* meta cap data. It should only change the address. JALR should install a new *expanded* meta cap data.

**Comment by davidchisnall** [comment]
> Storing PCC bounds as expanded is part of the spec now.

I think we need to be a bit careful here. I don’t want to require implementations to keep the bounds expanded, but I don’t mind if they need to act as if the bounds are expanded and handle PC-relative jumps that lead to unrepresentable values in a consistent and well-defined way.

**Comment by vmurali** [comment]
> I think we need to be a bit careful here. I don’t want to require implementations to keep the bounds expanded, but I don’t mind if they need to act as if the bounds are expanded and handle PC-relative jumps that lead to unrepresentable values in a consistent and well-defined way.

If they are not stored expanded, the new PCC may not have any bearing to the previous PCC w.r.t. representability. A more complicated spec would be what I had outlined - compare the new PCC's address on JAL and Branch with the previous PCC's bounds. I believe both are equivalent (and storing the previous PCC in the spec is more complex in my opinion).
